project_id = "rgmzmtsgpxxzxvdcwsdx"

[functions.get-market-previews]
verify_jwt = false

[functions.polymarket-data]
verify_jwt = false

[functions.market-dashboard]
verify_jwt = false

[functions.poly-chat]
verify_jwt = false

[functions.leaderboard]
verify_jwt = false

[functions.builder-stats]
verify_jwt = false

[functions.fetch-news]
verify_jwt = false

[functions.whale-tracker]
verify_jwt = false

[functions.wallet-profile]
verify_jwt = false

[functions.resolve-market-url]
verify_jwt = false

[functions.builder-sign]
verify_jwt = false

[functions.get-dome-api-key]
verify_jwt = false

[functions.dome-place-order]
verify_jwt = false

[functions.dome-router]
verify_jwt = false

[functions.dome-ws-url]
verify_jwt = false

[functions.get-user-positions]
verify_jwt = false

[functions.get-user-trades]
verify_jwt = false

[functions.get-open-orders]
verify_jwt = false

[functions.poly-trade]
verify_jwt = false

[functions.polymarket-live]
verify_jwt = false

[functions.queue-status]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.text-to-voice]
verify_jwt = false

[functions.twitter-poll-mentions]
verify_jwt = false

[functions.update-cache]
verify_jwt = false

[functions.update-leaderboard-cache]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.wallet-analytics]
verify_jwt = false

[functions.generate-hmac]
verify_jwt = false

[functions.dome-user-data]
verify_jwt = false

[functions.cancel-order]
verify_jwt = false
